# Generated by Django 5.1.3 on 2024-12-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostJob',
        ),
    ]
